# Generated by Django 3.1.5 on 2021-02-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='projecturl',
            new_name='companyurl',
        ),
        migrations.DeleteModel(
            name='Revieww',
        ),
    ]
