# Generated by Django 3.1.5 on 2021-02-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210204_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='location',
            field=models.CharField(default='', max_length=30),
        ),
    ]
