# Generated by Django 3.1.5 on 2021-02-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projects_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='title',
            new_name='Job_type',
        ),
    ]
