# Generated by Django 3.1.5 on 2021-02-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210205_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='contacts',
            field=models.CharField(default='', max_length=30),
        ),
    ]
